global using GraduationProjectWebApi.Models.Hotels;
global using GraduationProjectWebApi.Abstraction;
global using GraduationProjectWebApi.Models.Flights;
global using GraduationProjectWebApi.Models.Offers;
global using Microsoft.EntityFrameworkCore;
global using GraduationProjectWebApi.Models;
global using System.Text.Json.Serialization;
global using GraduationProjectWebApi.Models.Enums;
global using GraduationProjectWebApi.DTOS;